User.create(email: "user@one", password: "oneuser")
User.create(email: "user@two", password: "twouser")
User.create(email: "user@three", password: "threeuser")
User.create(email: "user@four", password: "fouruser")
User.create(email: "user@five", password: "fiveuser")
User.create(email: "user@six", password: "sixuser")
User.create(email: "user@seven", password: "sevenuser")
User.create(email: "user@eight", password: "eightuser")
User.create(email: "user@nine", password: "nineuser")
User.create(email: "user@ten", password: "tenuser")


Genre.create(name: "Rock")
Genre.create(name: "Jazz")
Genre.create(name: "Reggae")
Genre.create(name: "Electro")
Genre.create(name: "Soul")
Genre.create(name: "Classique")
Genre.create(name: "Contemporain")
Genre.create(name: "Metal")
Genre.create(name: "Hip hop")
Genre.create(name: "Folk")
Genre.create(name: "World")
Genre.create(name: "Ambiance")
Genre.create(name: "Edm")
Genre.create(name: "Country")
Genre.create(name: "Blues")
Genre.create(name: "Variété")


Band.create(price:"1000",name:"Los Fralibos",city:"Marseille",conditions:"", user_id: 1,genre_id: 1, remote_image_url:"https://img.cdandlp.com/2018/06/imgL/1139048260.jpg")
Band.create(price:"2000",name:"Digital Village",city:"Marseille",conditions:"", user_id: 2,genre_id: 4, remote_image_url:"https://img.cdandlp.com/2018/04/imgL/119125564.jpg")
Band.create(price:"3000",name:"Les Bouchons",city:"Lyon",conditions:"", user_id: 3,genre_id: 15, remote_image_url:"https://lemballageecologique.com/wp-content/uploads/2011/04/bouchons-de-liege-1.jpg")
Band.create(price:"23456",name:"Max Kansas City Band",city:"Marseille",conditions:"", user_id: 4,genre_id: 1, remote_image_url:"https://image.spreadshirtmedia.com/image-server/v1/mp/products/T210A2MPA3176PT17X0Y4D1017876395FS3464/views/1,width=378,height=378,appearanceId=2,backgroundColor=F2F2F2,modelId=1543,crop=list,version=1542187553/max-s-kansas-city-retro-american-punk-70s-punk-cbg-men-s-t-shirt.jpg")
Band.create(price:"23456",name:"Clouzot",city:"Lille",conditions:"", user_id: 5,genre_id: 1, remote_image_url:"https://my.zikinf.com/_gfx/pochettes/1148-1347478654l.jpg")
Band.create(price:"23456",name:"Los Rancheros",city:"Clermont",conditions:"", user_id: 6,genre_id: 13, remote_image_url:"https://i.ytimg.com/vi/NOxMG845XvI/hqdefault.jpg")
Band.create(price:"10",name:"Arcelor",city:"Metz",conditions:"", user_id: 7,genre_id: 8, remote_image_url:"http://georgiamusic.org/wp-content/uploads/2017/09/Fozzy.jpg")
Band.create(price:"23456",name:"Les Castafiores",city:"Marseille",conditions:"", user_id:8,genre_id: 6, remote_image_url:"https://www.amorgen-maisondesvoix.fr/wp-content/uploads/2018/09/2018-LES-CASTAFIORES-ETC..._resized_1.jpg")
Band.create(price:"1000000",name:"Les Huezmen",city:"Alpe d'Huez",conditions:"", user_id: 9,genre_id: 12, remote_image_url:"https://focus.levif.be/medias/11900/6092829.jpg")
Band.create(price:"23456",name:"Swing Girls",city:"Marseille",conditions:"", user_id: 10,genre_id: 2, remote_image_url:"https://www.kanpai.fr/sites/default/files/uploads/2008/07/swing-girls.jpg")



